export const birdsData = [
  {
    birdId: 'BIRD1',
    birdName: 'Charlie',
    birdAge: 3,
    status: 'Normal',
    species: 'Magpie-robin',
    cageId: 'CA001',
    foodQuantity: 200,
    periodId: 'PER002',
    birdGender: 'Male',
    hatchingDate: '2020-05-15',
    attitudes: 'Friendly',
    featherColor: 'Black and White',
    appearance: 'Small and agile',
    qualities: 'Good singer'
  },
  {
    birdId: 'BIRD2',
    birdName: 'Lucy',
    birdAge: 2,
    status: 'Sick',
    species: 'Magpie-robin',
    cageId: 'CA003',
    foodQuantity: 150,
    periodId: 'PER001',
    birdGender: 'Female',
    hatchingDate: '2021-02-28',
    attitudes: 'Shy',
    featherColor: 'Gray and White',
    appearance: 'Medium-sized',
    qualities: 'Good foragers'
  },
  {
    birdId: 'BIRD3',
    birdName: 'Oscar',
    birdAge: 4,
    status: 'Birth',
    species: 'Magpie-robin',
    cageId: 'CA005',
    foodQuantity: 180,
    periodId: 'PER003',
    birdGender: 'Female',
    hatchingDate: '2019-11-10',
    attitudes: 'Playful',
    featherColor: 'Black and White',
    appearance: 'Medium-sized',
    qualities: 'Good foragers'
  },
  {
    birdId: 'BIRD4',
    birdName: 'Milo',
    birdAge: 2,
    status: 'Normal',
    species: 'Red-whispered bulbul',
    cageId: 'CA002',
    foodQuantity: 250,
    periodId: 'PER001',
    birdGender: 'Female',
    hatchingDate: '2021-08-03',
    attitudes: 'Active',
    featherColor: 'Red and Brown',
    appearance: 'Small and colorful',
    qualities: 'Excellent flyer'
  },
  {
    birdId: 'BIRD5',
    birdName: 'Buddy',
    birdAge: 5,
    status: 'Sick',
    species: 'Red-whispered bulbul',
    cageId: 'CA004',
    foodQuantity: 220,
    periodId: 'PER003',
    birdGender: 'Male',
    hatchingDate: '2018-12-20',
    attitudes: 'Sociable',
    featherColor: 'Red and Brown',
    appearance: 'Medium-sized and vocal',
    qualities: 'Good singer'
  },
  {
    birdId: 'BIRD6',
    birdName: 'Coco',
    birdAge: 1,
    status: 'Birth',
    species: 'Red-whispered bulbul',
    cageId: 'CA005',
    foodQuantity: 190,
    periodId: 'PER001',
    birdGender: 'Female',
    hatchingDate: '2022-04-05',
    attitudes: 'Curious',
    featherColor: 'Red and Brown',
    appearance: 'Small and colorful',
    qualities: 'Active and vocal'
  },

  {
    birdId: 'BIRD7',
    birdName: 'Janet',
    birdAge: 4,
    status: 'Birth',
    species: 'White-rumped Shama',
    cageId: 'CA005',
    foodQuantity: 220,
    periodId: 'PER003',
    birdGender: 'Female',
    hatchingDate: '2019-09-15',
    attitudes: 'Gentle',
    featherColor: 'Gray and White',
    appearance: 'Medium-sized and melodious',
    qualities: 'Excellent singer'
  },
  {
    birdId: 'BIRD8',
    birdName: 'Max',
    birdAge: 3,
    status: 'Sick',
    species: 'White-rumped Shama',
    cageId: 'CA003',
    foodQuantity: 240,
    periodId: 'PER002',
    birdGender: 'Male',
    hatchingDate: '2020-07-25',
    attitudes: 'Energetic',
    featherColor: 'Gray and White',
    appearance: 'Medium-sized and vocal',
    qualities: 'Good foragers'
  },
  {
    birdId: 'BIRD9',
    birdName: 'Laura',
    birdAge: 1,
    status: 'Normal',
    species: 'White-rumped Shama',
    cageId: 'CA001',
    foodQuantity: 250,
    periodId: 'PER001',
    birdGender: 'Female',
    hatchingDate: '2022-01-12',
    attitudes: 'Friendly',
    featherColor: 'Gray and White',
    appearance: 'Small and melodious',
    qualities: 'Good singer'
  },
  {
    birdId: 'BIRD10',
    birdName: 'Rocky',
    birdAge: 4,
    status: 'Normal',
    species: 'White-rumped Shama',
    cageId: 'CA002',
    foodQuantity: 270,
    periodId: 'PER003',
    birdGender: 'Male',
    hatchingDate: '2019-05-30',
    attitudes: 'Active',
    featherColor: 'Gray and White',
    appearance: 'Medium-sized and melodious',
    qualities: 'Excellent flyer'
  },
  {
    birdId: 'BIRD11',
    birdName: 'Luna',
    birdAge: 2,
    status: 'Sick',
    species: 'White-rumped Shama',
    cageId: 'CA004',
    foodQuantity: 230,
    periodId: 'PER001',
    birdGender: 'Female',
    hatchingDate: '2021-11-18',
    attitudes: 'Playful',
    featherColor: 'Gray and White',
    appearance: 'Small and vocal',
    qualities: 'Good foragers'
  },
  {
    birdId: 'BIRD12',
    birdName: 'Misty',
    birdAge: 3,
    status: 'Normal',
    species: 'White-rumped Shama',
    cageId: 'CA001',
    foodQuantity: 290,
    periodId: 'PER002',
    birdGender: 'Female',
    hatchingDate: '2020-09-03',
    attitudes: 'Sociable',
    featherColor: 'Gray and White',
    appearance: 'Medium-sized and melodious',
    qualities: 'Excellent singer'
  },
  {
    birdId: 'BIRD13',
    birdName: 'Cooper',
    birdAge: 1,
    status: 'Birth',
    species: 'Seychelles magpie-robin',
    cageId: 'CA005',
    foodQuantity: 310,
    periodId: 'PER001',
    birdGender: 'Male',
    hatchingDate: '2022-03-10',
    attitudes: 'Energetic',
    featherColor: 'Gray and White',
    appearance: 'Small and vocal',
    qualities: 'Good singer'
  },
  {
    birdId: 'BIRD14',
    birdName: 'Zoe',
    birdAge: 4,
    status: 'Sick',
    species: 'Seychelles magpie-robin',
    cageId: 'CA003',
    foodQuantity: 270,
    periodId: 'PER003',
    birdGender: 'Female',
    hatchingDate: '2019-07-02',
    attitudes: 'Curious',
    featherColor: 'Gray and White',
    appearance: 'Medium-sized and melodious',
    qualities: 'Good foragers'
  },

  {
    birdId: 'BIRD15',
    birdName: 'Lucky',
    birdAge: 2,
    status: 'Normal',
    species: 'Seychelles magpie-robin',
    cageId: 'CA002',
    foodQuantity: 250,
    periodId: 'PER001',
    birdGender: 'Male',
    hatchingDate: '2021-01-30',
    attitudes: 'Active',
    featherColor: 'Gray and White',
    appearance: 'Medium-sized and vocal',
    qualities: 'Sociable and good foragers'
  }

];
