export const birdsData = [
  {
    birdId: 'BIRD001',
    birdName: 'Charlie',
    birdAge: 3,
    status: 'Normal',
    species: 'Magpie-robin',
    cageId: 'CA001',
    foodQuantity: 200,
  },
  {
    birdId: 'BIRD002',
    birdName: 'Lucy',
    birdAge: 2,
    status: 'Sick',
    species: 'Magpie-robin',
    cageId: 'CA001',
    foodQuantity: 150,
  },
  {
    birdId: 'BIRD003',
    birdName: 'Oscar',
    birdAge: 4,
    status: 'Birth',
    species: 'Magpie-robin',
    cageId: 'CA001',
    foodQuantity: 180,
  },
  {
    birdId: 'BIRD004',
    birdName: 'Milo',
    birdAge: 2,
    status: 'Normal',
    species: 'Red-whispered bulbul',
    cageId: 'CA002',
    foodQuantity: 250,
  },
  {
    birdId: 'BIRD005',
    birdName: 'Buddy',
    birdAge: 5,
    status: 'Sick',
    species: 'Red-whispered bulbul',
    cageId: 'CA002',
    foodQuantity: 220,
  },
  {
    birdId: 'BIRD006',
    birdName: 'Coco',
    birdAge: 1,
    status: 'Birth',
    species: 'Red-whispered bulbul',
    cageId: 'CA002',
    foodQuantity: 190,
  },
  {
    birdId: 'BIRD007',
    birdName: 'Bella',
    birdAge: 2,
    status: 'Normal',
    species: 'White-rumped Shama',
    cageId: 'CA003',
    foodQuantity: 280,
  },
  {
    birdId: 'BIRD008',
    birdName: 'Max',
    birdAge: 3,
    status: 'Sick',
    species: 'White-rumped Shama',
    cageId: 'CA003',
    foodQuantity: 240,
  },
  {
    birdId: 'BIRD009',
    birdName: 'Daisy',
    birdAge: 2,
    status: 'Birth',
    species: 'White-rumped Shama',
    cageId: 'CA003',
    foodQuantity: 210,
  },
  {
    birdId: 'BIRD010',
    birdName: 'Rocky',
    birdAge: 4,
    status: 'Normal',
    species: 'White-rumped Shama',
    cageId: 'CA004',
    foodQuantity: 270,
  },
  {
    birdId: 'BIRD011',
    birdName: 'Luna',
    birdAge: 2,
    status: 'Sick',
    species: 'White-rumped Shama',
    cageId: 'CA004',
    foodQuantity: 230,
  },
  {
    birdId: 'BIRD012',
    birdName: 'Misty',
    birdAge: 3,
    status: 'Normal',
    species: 'White-rumped Shama',
    cageId: 'CA004',
    foodQuantity: 290,
  },
  {
    birdId: 'BIRD013',
    birdName: 'Cooper',
    birdAge: 1,
    status: 'Birth',
    species: 'Seychelles magpie-robin',
    cageId: 'CA005',
    foodQuantity: 310,
  },
  {
    birdId: 'BIRD014',
    birdName: 'Zoe',
    birdAge: 4,
    status: 'Sick',
    species: 'Seychelles magpie-robin',
    cageId: 'CA005',
    foodQuantity: 270,
  },
  {
    birdId: 'BIRD015',
    birdName: 'Lucky',
    birdAge: 2,
    status: 'Normal',
    species: 'Seychelles magpie-robin',
    cageId: 'CA005',
    foodQuantity: 250,
  },

];
