export const tasks = [
    {
        id: 1,
        title: "Feed the birds",
        description: "Regular feeding of all birds in the aviary",
        staffId: "STA001",
        location: "Normal",
        status: "Feeded",
    },
    {
        id: 2,
        title: "Administer medication",
        description: "Administer prescribed medication to sick birds",
        staffId: "STA002",
        location: "Sick",
        status: "Pending",
    },
    {
        id: 3,
        title: "Welcome new arrivals",
        description: "Prepare birthing area for the arrival of new birds",
        staffId: "STA003",
        location: "Birth",
        status: "Feeding Late",
    },
    {
        id: 4,
        title: "Exotic bird care",
        description: "Special care for exotic birds in a separate enclosure",
        staffId: "STA004",
        location: "Exotic",
        status: "Pending",
    },
    {
        id: 5,
        title: "Clean bird cages",
        description: "Thoroughly clean and sanitize all bird cages",
        staffId: "STA001",
        location: "Normal",
        status: "Feeded",
    },
    {
        id: 6,
        title: "Veterinary checkup",
        description: "Schedule and take birds for routine veterinary checkups",
        staffId: "STA002",
        location: "Normal",
        status: "Pending",
    },
    {
        id: 7,
        title: "Incubate eggs",
        description: "Monitor and maintain incubation of bird eggs in the hatchery",
        staffId: "STA003",
        location: "Birth",
        status: "Feeding Late",
    },
    {
        id: 8,
        title: "Exotic bird showcase",
        description: "Prepare and showcase exotic birds for educational events",
        staffId: "STA004",
        location: "Exotic",
        status: "Pending",
    },
    {
        id: 9,
        title: "Sick bay care",
        description: "Provide care and monitoring for birds in the sick bay",
        staffId: "STA002",
        location: "Sick",
        status: "Feeded",
    },
];
